### ISSUE TITLE
如果不输入 www 无法重定向

### ISSUE THREAD

**Issue by paladin-t** [pengan1987/computer-museum-dnbwg#1]
重现方法：[dnbwg.com](http://dnbwg.com/)
做为访问者，有时候想直接输入 www 后面的东西。

**Comment by pengan1987** [comment]
这个应该是Godaddy的重定向服务的限制，这个网站是无后端的，根域名重定向到www，www用CNAME指向阿里云OSS存储容器，解除这个限制的话，需要做根域名CNAME，但Godaddy的DNS设置不支持这个功能。

**Comment by pengan1987** [comment]
我把网站换用了CloudFlare的CNAME Flattening，应该可以不用www了。
