### ISSUE TITLE
吞食天地

### ISSUE THREAD

**Issue by SuperZiLu** [pengan1987/computer-museum-dnbwg#10]
为什么没有吞食天地啊 这么经典的小霸王游戏 建议添加。

**Comment by pengan1987** [comment]
吞食天地系列是Capcom在红白机上正式发行的游戏，由于任天堂及日本开发商通常对模拟器社区对旧ROM的利用不宽容，社区能够提供的红白机游戏仅限于：
1、曾经销售，但不通过任天堂渠道发行过的游戏
2、计划通过任天堂发行，但未正式发表过的游戏
3、由社区开发的独立游戏

**Comment by SuperZiLu** [comment]
> 吞食天地系列是Capcom在红白机上正式发行的游戏，由于任天堂及日本开发商通常对模拟器社区对旧ROM的利用不宽容，社区能够提供的红白机游戏仅限于：
> 1、曾经销售，但不通过任天堂渠道发行过的游戏
> 2、计划通过任天堂发行，但未正式发表过的游戏
> 3、由社区开发的独立游戏

受教了 感谢回复！
