### ISSUE TITLE
APPLE-II 的计算机的普及从娃娃抓起的ROM挂了

### ISSUE THREAD

**Issue by Dawn-Xu-helloworld** [pengan1987/computer-museum-dnbwg#11]

**Comment by Dawn-Xu-helloworld** [comment]
我实在找不到联系你的方式了，只能发个issues了

**Comment by pengan1987** [comment]
我在浙江移动、浙江电信的网络下测试都是OK的，请检查你的网络下面两个域名是否解析正常。
dnbwg.cdn.bcebos.com
dnbwg2.cdn.bcebos.com

**Comment by pengan1987** [comment]
Checked this issue and can't reproduce, may caused by visitor's connectivity issue. Close this issue.
