### ISSUE TITLE
提议添加最早的 Windows 测试版

### ISSUE THREAD

**Issue by DevScholar** [pengan1987/computer-museum-dnbwg#12]
您好，我认为添加最早的 Windows 测试版是有意义的，可以用来了解计算机历史。
目前，最早的可用的 Windows 测试版是 [Windows 1.0 DR5](https://winworldpc.com/product/windows-10/dr-5)。如果未来有更早的版本可用，就用更早的版本替换。
Windows 1.0 DR5 太旧了，可能不能用 DOSBox 运行，而要用 [pcjs](https://www.pcjs.org/)+MS-DOS 2.x 或 3.0 运行。

**Comment by pengan1987** [comment]
Add Windows 1.0 DR5 with DOSBox+DOS 2.11 boot disk+10MB HDD image+modified mouse driver
For more information for the mouse driver check vio08's post here:
https://forum.winworldpc.com/discussion/10956/windows-1-0-dr-5/p2
