### ISSUE TITLE
提议增加共创linux展览

### ISSUE THREAD

**Issue by akra3523** [pengan1987/computer-museum-dnbwg#13]
共创linux（又名OpenDesktop开放桌面）是一个2003——2005年期间活跃的一个国产发行版，希望能在电脑博物馆新增该发行版体验
该发行版iso：https://archive.org/details/CoCreateLinux103
另注：该发行版目前确认只有1.0.3版可正常下载使用，其余版本皆无法使用或失传，不知能否通过您的影响力能让该发行版的后续版本重见光明？谢谢！

**Comment by akra3523** [comment]
最近我挖掘了一点资料，网上有流传出2005版本的共创linux，但是镜像是损坏无法启动的，不过我经过尝试抢救之后发现这个版本实际上是1.0.3版本的更新维护，UI大致上没有区别
目前想询问能否重新找到OpenDesktop-i386-disc.iso以及Baby2-i386-disc-SP1-20051206.iso这个发行版的资源？万分感谢！

**Comment by pengan1987** [comment]
共创Linux对于“千禧年的中文Linux”所希望表达的主题来说太新了。
2000年前后的中文Linux的主要挑战仍然是中文显示和处理的问题，您可以尝试搜索当年关于《警惕LINUX内核汉化带来的误导》相关的讨论，以及混杂着的民族情绪和正盗版之争
《警惕“LINUX內核漢化”帶來的誤導》http://www.unixlinux.online/unixlinux/gdliunx/linuxnh/201702/15280.html
评<警惕"内核汉化"带来的误导>一文  http://att.newsmth.net/bbsanc.php?path=%2Fgroups%2Fcomp.faq%2FLinuxDev%2Fi18n%2Fi18n-discuss%2FM.943058697.A
《打盗版打跑正版 Linux风起云涌渔翁得利》 http://tech.sina.com.cn/it/e/2002-01-14/99430.shtml
《IBM预装Linux操作系统事件引发Linux争论》http://tech.sina.com.cn/it/w/2002-11-01/1822147514.shtml

我在v2ex的帖子里提到过在这一话题范围但没找到的几个发行版，比如中软 Linux（3.0之前） 、即時 Linux等、Turbolinux（中文版6.0或之前），都要求早期版本 https://www.v2ex.com/t/659818
