### ISSUE TITLE
Mobile Version Support

### ISSUE THREAD

**Issue by KevZhi** [pengan1987/computer-museum-dnbwg#2]
Provide a button to show keyboard or joystick emulation
(So far only saw on Wenquxing and few others)
Provide a button to adjust screen ratio 
Check compatibility with mobile browsers
( Subor Emulator crashes on Safari on iOS)

Thank you for your fantastic work!

**Comment by pengan1987** [comment]
Added a button to resize the canvas fit to screen
Added a button to show system built in "password" (alphanumeric, no emoji etc.) keyboard
Still looking for a way to show more usable virtual keyboard (fn/direction/ctrl/alt/meta keys etc) on mobile browser

**Comment by pengan1987** [comment]
most computers required a keyboard to operate, no plan for further mobile adoption
