### ISSUE TITLE
Sharp X1turbo emulator X millennium ported to Emscripten

### ISSUE THREAD

**Issue by yksoft1** [pengan1987/computer-museum-dnbwg#3]
Sharp X1turbo is a Z80-based home computer that competed with PC-8801.
X millennium is an early X1turbo emulator originated from early 2000s, with a Windows and SDL2 frontend based on Neko Project II's.

https://github.com/yksoft1/xmil/tree/emscripten
Demo:
https://yksoft1.github.io/emularity/xmil/xmil.html

Xmil's SDL2 frontend accepts floppy disk boot image from command line, so it should be easy to port to use Emularity.

**Comment by pengan1987** [comment]
Cool! Will include that in next update.
I see there is a new NP2Loader implemented in your loader.js, could you also open a pull request to https://github.com/db48x/emularity ?

**Comment by yksoft1** [comment]
> I see there is a new NP2Loader implemented in your loader.js, could you also open a pull request to https://github.com/db48x/emularity ?

I remember NP2Loader is just a simple hack I did porting Neko Project II to Emscripten and I don't want to touch it anymore.  It's up to you for reimplementing it. 
X millennium accepts the first command line argument as the path of a boot disk image file.

**Comment by pengan1987** [comment]
SHARP X1 Turbo added
