### ISSUE TITLE
提议添加废土

### ISSUE THREAD

**Issue by paladin-t** [pengan1987/computer-museum-dnbwg#4]
[wasteland](https://en.wikipedia.org/wiki/Wasteland_(video_game))

**Comment by pengan1987** [comment]
目前仍然以添加新的机型为主，会在以后增加更多游戏

**Comment by pengan1987** [comment]
目前已有收集dos游戏的专门网站，网页里的电脑博物馆目前没有继续添加dos游戏的计划。
