### ISSUE TITLE
我注意您的知乎专栏上使用了来自我的blog的照片

### ISSUE THREAD

**Issue by sswv** [pengan1987/computer-museum-dnbwg#5]
您好，我注意您的[知乎专栏](https://zhuanlan.zhihu.com/p/53700861)上使用了来自我的[blog](https://linjian.org/blog/tech/linux/distro/old-linux-distro-1)的照片（蓝点Linux），但没有说明出处。我的blog上有关Linux发行版的照片皆为本人拍摄，网页上已说明使用CC BY-NC-SA 4.0授权发布，因此请您注明出处。

我手头有blog文章提到的部分Linux发自版的ISO镜像，如有兴趣可找我要。

**Comment by pengan1987** [comment]
已经著名出处并将您的blog链接加入到文章中，是否可以分享您提到的部分Linux发行版镜像？或者有条件的话，可以将其上传到archive.org保存，谢谢您的支持！

**Comment by sswv** [comment]
我也愿意将我收藏的一些Linux镜像分享出来。我有空研究一下archive.org的共享机制及版权相关事项。

**Comment by pengan1987** [comment]
No updates for this issue, close.
