### ISSUE TITLE
Netscape不能正常模拟

### ISSUE THREAD

**Issue by SyzygyYuan** [pengan1987/computer-museum-dnbwg#6]
http://www.dnbwg.com/v86.html?machine=netscape
会卡在Windows95的界面后

**Comment by SyzygyYuan** [comment]
还有一些话，不知写在这里合不合适，因为我知乎账号没有了，只好到Github来留言。
今天我去了一趟中关村的创业博物馆，和那边的负责人交谈之后，才发现原来经营线上电脑博物馆的您也参与其中。当时我对运行《中关村启示录》的机器很有兴趣，因为我自己尝试在DOSBox中模拟却没有成功过，而一个相近的项目（指https://dos.zczc.cz ）也有类似的问题。我当时以为是直接运行在机器上的DOS环境，就尝试退出游戏，看看硬盘的内容，然后试图运行autoexec重新进入游戏，却卡住了，请工作人员帮忙后才发现其实也是在DOSBox中运行的。所以我想了解的是，为了成功模拟《中关村启示录》，是不是需要什么特殊的配置？此外，我试用了场馆里展出的裕兴学习机，现在想想，那也是模拟器吧。在您知乎专栏内看到裕兴曾经出过官方模拟器，不知您说的存档有人找到了没有。
另外，我几年前看过yang leaonier的回答（https://www.zhihu.com/question/20528367/answer/67532610 ）里，出现过虚拟机内的CCDOS4.0系统，这也是一个我尝试模拟而不曾成功的软件。如果可以，希望您也能在电脑博物馆里加入带汉化了的WordStar的CCDOS系统，
对世纪末出生的我来说，关于过去的机器和软件的知识，以前完全来自于书本。现在呢，我甚至可以到博物馆实际看一看这些旧机器，您的网上电脑博物馆则给了我们机会接触到更多过去的软件。希望您的网上电脑博物馆能越办越好！

**Comment by pengan1987** [comment]
我在Windows 10 + Chrome 77的环境下试验Netscape是可以正常使用的，使用Edge浏览器也可以允许，不过比较慢，能发一下详细的系统环境和控制台日志吗？
中关村启示录在DOSBox下运行需要预先加载DMOUSE鼠标驱动，在百度搜索 中关村启示录 鼠标驱动 就可以找到
DOSBox运行中文系统通常不能直接运行，而是需要使用boot命令使用真实的MS-DOS/PC-DOS启动盘镜像启动，再运行中文环境，电脑博物馆里的UCDOS就是这么启动的。
yang leaonier的回答中使用的是PCem，是一款真实模拟旧款PC硬件的模拟器，使用老PC的原始BIOS，拟真程度更高。

**Comment by SyzygyYuan** [comment]
确认了，是我的Chrome版本太旧了，现在可以了。
